project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - slides/chapters/00.qmd
    - slides/chapters/01.qmd
    - slides/chapters/02.qmd
    - slides/chapters/03.qmd
    - slides/chapters/04.qmd
    - slides/chapters/05.qmd
    - slides/chapters/06.qmd
    - slides/chapters/07.qmd
    - slides/chapters/08.qmd
    - slides/chapters/09.qmd
    - slides/chapters/10.qmd
  resources:
    - .nojekyll
    - downloads/*.pdf
    - images/final/*.svg
    - images/finance-header-img.png
    - vendor/mathjax/*
execute:
  freeze: false
  cache: false
website:
  title: "Kurs 100 · Finansiering 2026"
  site-url: https://lehfinancier.github.io/Finansiering-2026/
  repo-url: https://github.com/Lehfinancier/Finansiering-2026
  repo-subdir: src
  search: true
  navbar:
    title: "KURS 100"
    left:
      - text: "Kursusinfo"
        href: index.qmd#kursusinformation
      - text: "Lektionsplan"
        href: index.qmd#lektionsplan
      - text: "Kapitler"
        href: index.qmd#kapitler
      - text: "Lektionsnoter"
        href: downloads/Kurs100-2026.pdf
      - text: "Øvelser"
        href: index.qmd#oevelser
  page-footer: "Finansiering · HA.jur. · Niklas Lehmann Jensen"
format:
  html:
    theme: [cosmo, themes/kurs100-site.scss]
    toc: false
    anchor-sections: true
    embed-resources: true
lang: da
